version: "3.8"
services:
  api:
    build: ./api
    container_name: nodejs-api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  react-app:
    build: ./react-simple-app
    container_name: react-app_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./react-simple-app:/app
      - /app/node_modules


